copyright: The NTFSSecurity module is licensed under the <a href='https://github.com/raandree/NTFSSecurity/blob/master/LICENSE'>MIT license
repo_url: https://github.com/raandree/NTFSSecurity
nav:
- Home: ./Index.md
site_name: NTFSSecurity
theme: readthedocs
site_author: Raimund Andrée, James Smith
docs_dir: ./Docs